# Base contributor/developer environment for kanoa-mlops
# For GCP infrastructure contributors, use environment-gcp.yml instead
name: kanoa-mlops
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  # Linting
  - shellcheck
  # Utilities
  - curl
  - jq
  - pip:
      - -e ".[dev]"
